name: Deploy main to production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: Build
      run: make build
    - name: Install npm dependencies
      run: npm install
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::[your-account-id]:role/[your-role-name]
        aws-region: us-east-1
    - name: Serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage production