service: lambda-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9.15

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements


custom:
  pythonRequirements:
    dockerizePip: true
#    dockerImage: python:3.10.8-buster
    zip: true