service: lambda-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9.15

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
  pythonBin: python3
  dockerizePip: "false"
