service: lambda-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements


custom:
  pythonRequirements:
    dockerImage: python:3.9.15-buster