on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
#    - name: Update
#      run: |
#        sudo apt-get update
#    - name: Install build-essential
#      run: |
#        sudo apt-get install -y build-essential
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
#    - name: Test python
#      run: |
#        echo $(python --version)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#    - name: Install PyTest
#      run: |
#          pip install pytest==4.6.11
#    - name: Test with pytest
#      run: |
#          pytest
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}